### ISSUE TITLE
self.description issue

### ISSUE THREAD

**Issue by mesh-newbie** [jinxo13/FetchTV-Helpers#2]
Hi @jinxo13 . Nice script. Exactly what i have been looking for.
Have noticed for me that the script bombs at:
`self.description = xml.find("./{urn:schemas-upnp-org:metadata-1-0/DIDL-Lite/}description").text`
Have temporarily done the following to bypass the item that doesn't contain an object with ".text".
`
desc = xml.find("./{urn:schemas-upnp-org:metadata-1-0/DIDL-Lite/}description")
 self.description = desc.text if desc is not None and desc.text else desc
`
Thanks
C

**Comment by jinxo13** [comment]
Thanks @mesh-newbie - I've made some changes to fix this
