### ISSUE TITLE
suggestion: file download progress

### ISSUE THREAD

**Issue by mesh-newbie** [jinxo13/FetchTV-Helpers#3]
Hi @jinxo13.
Suggestion for file progress download.
`
from clint.textui import progress
total_length = int(r.headers.get('content-length'))
for chunk in progress.bar(r.iter_content(chunk_size=8192), expected_size=(total_length/8192) + 1): 
`

**Comment by jinxo13** [comment]
Hi @mesh-newbie, great idea I've incorporated your code.
