### ISSUE TITLE
FetchTV Commands

### ISSUE THREAD

**Issue by staraxis** [jinxo13/FetchTV-Helpers#6]
Hi @jinxo13 thanks for the code! I stumbled across it as I recently got a Fetch Mighty.

I was wondering if you knew a way to send commands to the Fetch Box via python? Such as channel up/down, number presses etc?

I know there is an iOS app but I haven't sniffed any of the traffic yet.

Thanks for your advice. Cheers!

**Comment by jinxo13** [comment]
Hi @staraxis,
I had a search and couldn't find anything available in this area.

Looking at the Android app I could see it makes HTTPS calls to apis.fetchtv.com.au, messages.fetchtv.com.au, vcasott.fetchtv.com.au. It looks like the calls are encrypted.

There may be some useful information here: https://forums.whirlpool.net.au/archive/96pkl1p9 
This details information related to attempts to hack into the FetchTV.

Cheers,
Hamish

**Comment by jinxo13** [comment]
I've made some good progress on this, stay tuned...

**Comment by jinxo13** [comment]
I've now published a library that can do this: https://github.com/jinxo13/pyfetchtv

As well as a WebUI that uses it: https://github.com/jinxo13/FetchTVWeb

**Comment by furey** [comment]
Hi @jinxo13,

Great work on those repos—I've just spun up `FetchTVWeb` in Docker and it's really nicely done.

Cheers!

**Comment by jinxo13** [comment]
Hi @furey, great to hear. My next plan was to add the ability to mark channels as favorites, and default to them for recording. As well as add Alexa integration at some point.

**Comment by furey** [comment]
Wow! Looking forward to seeing where you take it, @jinxo13!

As a tip for the success of your `FetchTVWeb` repo I suggest adding some screenshots to the README, and perhaps making it Docker Compose-able. Were you planning on pushing an official image to [Docker Hub](https://hub.docker.com)?
