### ISSUE TITLE
Running on Synology

### ISSUE THREAD

**Issue by samturner3** [jinxo13/FetchTV-Helpers#8]
Installed this on my synology nas; however getting this error trying to save. Examples given in readme are for windows, maybe its a linux path name thing?

`>sudo python3 fetchtv_upnp.py --recordings --ip=10.40.17.94 --port=49152 --save"/volume1/PlexMedia/"`

```
Traceback (most recent call last):
  File "fetchtv_upnp.py", line 461, in <module>
    main(sys.argv)
  File "fetchtv_upnp.py", line 432, in main
    options = Options(argv)
  File "fetchtv_upnp.py", line 72, in __init__
    self.__dict['save'] = self.save.rstrip(os.path.sep)
AttributeError: 'bool' object has no attribute 'rstrip'
```

Tried a few path name variations like `--save"/volume1/PlexMedia"` etc

**Comment by jinxo13** [comment]
It needs the "=". I guess you already tried --save="/volume1/PlexMedia/"?

**Comment by mesh-newbie** [comment]
for me on catalina mac, i need the '=' and '.'   like so
sudo python3 fetchtv_upnp.py --recordings --ip=10.40.17.94 --port=49152 --save="./volume1/PlexMedia/"
also check that the volume is mapped :-)
diskutil list
